# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ytvideodownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YoutubeVideoDownloader_Form(object):
    def setupUi(self, YoutubeVideoDownloader_Form):
        YoutubeVideoDownloader_Form.setObjectName("YoutubeVideoDownloader_Form")
        YoutubeVideoDownloader_Form.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(YoutubeVideoDownloader_Form.sizePolicy().hasHeightForWidth())
        YoutubeVideoDownloader_Form.setSizePolicy(sizePolicy)
        YoutubeVideoDownloader_Form.setMinimumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setKerning(True)
        YoutubeVideoDownloader_Form.setFont(font)
        YoutubeVideoDownloader_Form.setMouseTracking(False)
        YoutubeVideoDownloader_Form.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("filmerror.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        YoutubeVideoDownloader_Form.setWindowIcon(icon)
        YoutubeVideoDownloader_Form.setWindowOpacity(1.0)
        YoutubeVideoDownloader_Form.setAutoFillBackground(False)
        YoutubeVideoDownloader_Form.setStyleSheet("#YoutubeVideoDownloader_Form{\n"
"border-image: url(:/back/background-image.jpg);}")
        self.pushButton_download = QtWidgets.QPushButton(YoutubeVideoDownloader_Form)
        self.pushButton_download.setEnabled(True)
        self.pushButton_download.setGeometry(QtCore.QRect(210, 250, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_download.setFont(font)
        self.pushButton_download.setAcceptDrops(False)
        self.pushButton_download.setAutoFillBackground(False)
        self.pushButton_download.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/indir/download_icon_128877.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_download.setIcon(icon1)
        self.pushButton_download.setCheckable(False)
        self.pushButton_download.setChecked(False)
        self.pushButton_download.setAutoRepeat(False)
        self.pushButton_download.setAutoExclusive(False)
        self.pushButton_download.setAutoDefault(False)
        self.pushButton_download.setDefault(False)
        self.pushButton_download.setFlat(False)
        self.pushButton_download.setObjectName("pushButton_download")
        self.lineEdit_URL = QtWidgets.QLineEdit(YoutubeVideoDownloader_Form)
        self.lineEdit_URL.setGeometry(QtCore.QRect(60, 60, 281, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit_URL.setFont(font)
        self.lineEdit_URL.setTabletTracking(False)
        self.lineEdit_URL.setAutoFillBackground(False)
        self.lineEdit_URL.setStyleSheet("")
        self.lineEdit_URL.setDragEnabled(False)
        self.lineEdit_URL.setReadOnly(False)
        self.lineEdit_URL.setClearButtonEnabled(False)
        self.lineEdit_URL.setObjectName("lineEdit_URL")
        self.checkBox_MP3 = QtWidgets.QCheckBox(YoutubeVideoDownloader_Form)
        self.checkBox_MP3.setGeometry(QtCore.QRect(60, 160, 70, 17))
        self.checkBox_MP3.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.checkBox_MP3.setObjectName("checkBox_MP3")
        self.checkBox_MP4 = QtWidgets.QCheckBox(YoutubeVideoDownloader_Form)
        self.checkBox_MP4.setGeometry(QtCore.QRect(60, 180, 70, 17))
        self.checkBox_MP4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_MP4.setObjectName("checkBox_MP4")
        self.label_2 = QtWidgets.QLabel(YoutubeVideoDownloader_Form)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 311, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(YoutubeVideoDownloader_Form)
        QtCore.QMetaObject.connectSlotsByName(YoutubeVideoDownloader_Form)

    def retranslateUi(self, YoutubeVideoDownloader_Form):
        _translate = QtCore.QCoreApplication.translate
        YoutubeVideoDownloader_Form.setWindowTitle(_translate("YoutubeVideoDownloader_Form", "Youtube Video Downloader"))
        self.pushButton_download.setText(_translate("YoutubeVideoDownloader_Form", "İndir"))
        self.lineEdit_URL.setPlaceholderText(_translate("YoutubeVideoDownloader_Form", "Youtube URL\'si giriniz."))
        self.checkBox_MP3.setText(_translate("YoutubeVideoDownloader_Form", "MP3"))
        self.checkBox_MP4.setText(_translate("YoutubeVideoDownloader_Form", "MP4"))
        self.label_2.setText(_translate("YoutubeVideoDownloader_Form", "*Hangi türde indirmek istediğinizi lütfen seçiniz."))
import icon_rc
